version: 2.1
executors:
  android-excutor:
    docker:
      - image: ciclerci/android:api-29
    working_directory: ~/guessword
    environment:
      JVM_OPTS: -Xmx3200m

jobs:
  build:
    executor: android-excutor
    step:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results